config/routes.rb
Rails.application.routes.draw do
  # get 'home/about'
  # get 'home/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'homes/top'
  root to: "home#top"
  devise_for :users

  # get 'books/new'
  # get 'books/index'
  # get 'books/show'
  resources :books,only:[:new,:create,:index,:show,:destroy,:edit,:update]
  # get 'users/show'
  # get 'users/edit'
  resources :users,only:[:show,:edit,:update,:index]

  get "home/about" => "home#about",as:'about'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_one_attached :profile_image

  # バリデーションの設定
  validates :name,length: {minimum:2,maximum:20},uniqueness: true
  validates :introduction,length: {maximum:50}

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width,height]).processed
  end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if create
      flash[:notice] = "Welcome! You have signed up successfully."
    else
      flash[:notice] = "Signed up failed."
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
    # super
    # if destroy
      # flash[:notice] = "Signed out successfully."
    # else
      # flash[:notice] = "Signed out failed."
    # end
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # ページネーション　1ページ分の数だけデータを取得する
    @books = @user.books.page(params[:page])
    # ↑　userに紐づいているbookがすべて取得、カラムを特定できないので、カラムの操作はできない
    # 部分テンプレートのためにbook/index同様に記述
    @book_new = Book.new
  end

  # Usersの表示のためindexを作成
  def index
    # ページネーション　すべてのデータではなく1ページ分の数のデータだけ取得する
    @users = User.page(params[:page])
    # 部分テンプレートのためにbook/index同様に記述
    @book_new = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.erb
<!--user/show → book/index から移動-->
<!--ユーザの詳細-->
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <!--btn-outline-secondaryで灰色の枠線-->
    <!--見本ではclassにedit_user_idにidが入っている-->
    <%= link_to edit_user_path(user.id),class:"btn btn-outline-secondary btn-block edit_user_id" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>


  <!--book/new.html.erbから移動-->
  <h2 class="mt-3">New book</h2>

  <!--@book = Book.new つながってない-->
  <%= form_with model:book_new do |f| %>
    <div class="form-group">
      <label for="book_title" class="mb-2">Title</label>
      <%= f.text_field :title,class:"form-control book_title" %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body,class:"form-control book_body" %>
    </div>
    <div class="form-group">
      <!--btn-successって名前のデザイン-->
      <%= f.submit "Create Book",class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <% if @user.errors.count == 1 %>
          <%= @user.errors.count %> error prohibited this obj from being saved:
        <% else %>
          <%= @user.errors.count %> errors prohibited this obj from being saved:
        <% end %>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>


      <%= form_with model:@user do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name,class:"form-control name" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image,class:"form-control-file user_image",accept:"image/*" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction,class:"form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User",class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--book/indexを引用。Userの一覧-->
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--部分テンプレート_user_infoを呼び出し-->
    <%= render 'users/user_info',{user: @user,book_new: @book_new} %>

<!--ユーザの投稿一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <!--table-hoverでカーソルを置くと色が変わる-->
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <!--該当userの投稿一覧画面のリンクを設定したい-->
            <!--見本ではclassにuser_idにidが入っている-->
            <td><%= link_to "Show",user_path(user.id),class:"user_id" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    <!--ページネーション-->
  <%= paginate @users %>
</div>

app/views/users/show.html.erb
<!--カリキュラムに記載の分はbooks/indexへ移動？ 特定userの投稿一覧は改めてこちらに -->
<!--実際の画面のuser/show＝user詳細は部分テンプレートとして、
view/users/_user_info.html.erbへ記載-->

<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <!--部分テンプレート_user_infoを呼び出し-->
      <%= render 'users/user_info',{user: @user,book_new: @book_new} %>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <!--table-hoverでカーソルを置くと色が変わる-->
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <!--見本ではclassにbook_idにidが入っている-->
              <td><%= link_to book.title,book_path(book.id),class:"book_id" %></td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>

        <!--ページネーション-->
        <%= paginate @books %>
      </div>
    </div>
  </div>
</main>