config/routes.rb
Rails.application.routes.draw do
  # get 'home/about'
  # get 'home/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'homes/top'
  root to: "home#top"
  devise_for :users

  # get 'books/new'
  # get 'books/index'
  # get 'books/show'
  resources :books,only:[:new,:create,:index,:show,:destroy,:edit,:update]
  # get 'users/show'
  # get 'users/edit'
  resources :users,only:[:show,:edit,:update,:index]

  get "home/about" => "home#about",as:'about'

end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  # バリデーションの設定
  validates :title, presence: true
  validates :body,length:{maximum:200},presence:true


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image.jpeg')
    end
    image
  end

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width,height]).processed
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  #投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.page(params[:page])
      @book_new = @book
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def index
    # ページネーション　すべてのデータではなく1ページ分の数のデータだけ取得する
    @books = Book.page(params[:page])
    @book_new = Book.new
    # bookからuser情報を取得したい、book/indexではログインユーザーを取得したい＝現在のユーザー
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    # @user = User.find(params[:id])
    # @books = @user.books
    # 部分テンプレート用にindexで使用したものと同じものを定義
    @book_new = Book.new
    # @bookで持ってきた特定userの情報がほしい
    @user = @book.user
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  # ストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<!--カリキュラムに沿って、部分テンプレートとして、book/indexから移動-->
<!--部分テンプレート要る？ってなったので、必要なところはbook/indexに直接記述してみる-->
<div class="card-list-container py-5">
  <% books.each do |book| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <!--<%= link_to book_path(book.id) do %>-->
      <!--<%= image_tag book.get_image, class:"card-img-top"; %>-->
    <!--<% end %>-->

    <div class="card-body">
      <!--userの画像は下の一文で表示できている?-->
      <p><%= image_tag book.user.get_profile_image(100,100) %></p>
      <!--タイトルとかの題名はついていないからデータ部分だけ記述する-->
      <!--一覧画面に詳細画面のリンクを設定-->
      <%= link_to book.title,book_path(book.id) %>
      <p><%= book.body %></p>
      <!--<p><%= book.user.name %></p>-->
    </div>
  </div>
  <% end %>

  <!--ページネーション-->
  <%= paginate books %>
</div>


<!--↓ をするためにはコントローラでif分岐が必要。資料として置いておく-->
<!--ログインユーザーが編集ボタンを押したら、users/editへ。
ログインユーザー以外のユーザーが編集ボタンを押したら、その人自身のuser.book/indexへ遷移-->
    <!--↓ログインユーザーIDと、現在のユーザーが一致していたら-->
  <!--% if user == current_user %>-->
    <!--%= link_to edit_user_path(user.id),class:"btn btn-edit",method: :get do %>-->
      <!--<i class="fa-solid fa-user-gear"></i>-->
    <!--% end %>-->
  <!--% else %>-->
    <!--%= link_to user_path(current_user),class:"btn btn-edit",method: :get do %>-->
      <!--<i class="fa-solid fa-user-gear"></i>-->
    <!--% end %>-->
  <!--% end %>-->

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <!--エラーメッセージの表示-->
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <% if @book.errors.count == 1 %>
              <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
            <% else %>
              <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
            <% end %>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>


      <%= form_with model:@book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title,class:"form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="body_opinion">Opinion</label>
          <%= f.text_area :body,class:"form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book",class:"btn btn-success" %>
        </div>
      <% end %>

        <!--↓ 見本はclassの中にbookのidが入っている-->
        <%= link_to "Show",book_path(@book),class:"book_id" %>
         |
        <%= link_to "Back",books_path,class:"back" %>
      </div>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<!--カリキュラムではuser/showへ記載になっていた部分-->
<div class="container px-5 px-sm-0">
<!--エラーメッセージの表示-->
<% if @book_new.errors.any? %>
  <div id="error_explanation">
    <% if @book_new.errors.count == 1 %>
      <h3><%= @book_new.errors.count %> error prohibited this obj from being saved:</h3>
    <% else %>
      <h3><%= @book_new.errors.count %> errors prohibited this obj from being saved:</h3>
    <% end %>
    <ul>
      <% @book_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="row">
    <!--部分テンプレート_user_infoを呼び出し-->
    <%= render 'users/user_info',{user: @user,book_new: @book_new} %>

<!--ユーザの投稿一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <!--table-hoverでカーソルを置くと色が変わる-->
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <!--userの画像は下の一文で表示できている?-->
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <!--一覧画面に詳細画面のリンクを設定-->
            <!--見本ではclassにbook_idにidが入っている-->
            <td><%= link_to book.title,book_path(book.id),class:"book_id" %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <!--ページネーション-->
      <%= paginate @books %>
    </div>
  </div>
</div>

<!--_list部分テンプレートへ → 部分テンプレートにせずに記述してみる-->
<!--%= render 'list',books: @books %>-->

app/views/books/new.html.erb
<!--部分テンプレートとして、
view/users/_user_info.html.erbへ記載を移動-->

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <!--部分テンプレート_user_infoを呼び出し-->
    <%= render 'users/user_info',{book: @book,book_new: @book_new,user: @user} %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <!--userの画像は下の一文で表示される？-->
      <!--%= image_tag @book.get_image %>-->
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %><br>
                <%= @book.user.name %>
              <% end %>
              <!--該当userの投稿一覧画面へのリンクへ-->
              <!--<%= link_to @book.user.name,user_path(@book.user.id) %>-->
            </td>
            <td><%= link_to @book.title,book_path(@book.id) %></td>
            <td><%= @book.body%></td>
            <td>
              <% if @book.user == current_user %>
                <!--%= link_to "Edit",edit_book_path(@book.id) %>-->
                <!--見本ではclassにedit_user_idにidが入っている-->
                <%= link_to edit_book_path(@book.id),class:"btn btn-success edit_book_id" do %>
                  Edit
                <% end %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <!--%= link_to "Destroy",book_path(@book),method: :delete %>-->
                <!--見本ではclassにdestroy_book_idにidが入っている-->
                <%= link_to book_path(@book),method: :delete, data: {confirm:"本当に消しますか？"},class:"btn btn-sm btn-danger destroy_book_id" do %>
                  Destroy
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <!--<p>%= @book.user.name %></p>-->
      <!--<p>%= @book.created_at.strftime('%Y/%m/%d') %></p>-->
    </div>
  </div>
</div>