config/routes.rb
Rails.application.routes.draw do
  # get 'home/about'
  # get 'home/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'homes/top'
  root to: "home#top"
  devise_for :users

  # get 'books/new'
  # get 'books/index'
  # get 'books/show'
  resources :books,only:[:new,:create,:index,:show,:destroy,:edit,:update]
  # get 'users/show'
  # get 'users/edit'
  resources :users,only:[:show,:edit,:update,:index]

  get "home/about" => "home#about",as:'about'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!--Bootstrap適用の為stylesheet部分変更。JabaScript配下ファイルを参照-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ログアウト機能などを設定-->
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <!--divise側が用意しているヘルパーメソッドで、
            ログインしている時true、ログインしていない場合falseの中が実行される-->
            <% if user_signed_in? %>
            <!--ログイン状態での表示-->
            <li>
              <%= link_to user_path(current_user.id),class:'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path,class:'nav-link text-light' do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path,class:'nav-link text-light' do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path,method: :delete, class:'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>

            <!--ログイン前の表示-->
            <% else %>
            <li>
              <%= link_to root_path,class:'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class:'nav-link text-light' do %>
                <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class:'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path,class:'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="notice mb-3">
        <!--successメッセージを表示するために、、-->
        <% if flash[:notice] %>
          <div class="flash">
            <%= flash[:notice] %>
          </div>
        <% end %>
      </div>

      <%= yield %>
    </main>

    <footer class="shadow-sm">
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p class="mb-3 text-center">CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>